---
version: "3.7"
services:
  frontend:
    build:
      context: .
      target: nodebase
    command: ["sh", "-c", "test -f node_modules/.bin/vue-cli-service || yarn install; yarn run serve"]
    ports:
      - "8080:8080"
    volumes:
      - "./web:/src"
  backend:
    build:
      context: .
      target: gobase
    command: ["modd", "--debug"]
    ports:
      - "3000:3000"
    volumes:
      - ".:/src"
