---
version: "3.7"
services:
  frontend:
    build:
      context: ./
      target: npmbase
    command: ["sh", "-c", "test -f node_modules/.bin/vue-cli-service || npm install; npm run serve"]
    ports:
      - "8080:8080"
    volumes:
      - "./web:/app/"
      - "/app/node_modules"
  backend:
    build:
      context: ./
      target: gobase
    command: ["modd", "--debug"]
    ports:
      - "3000:3000"
    volumes:
      - "./:/src"
      - "/go"
      - "/var/lib/bookmarks"
