name: Continious Integration
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Node Dependencies
      working-directory: web
      run: yarn install --no-progress
    - name: Go Dependencies
      run: go mod download
    - name: Node Lint
      working-directory: web
      run: yarn run lint --no-progress
    - name: Go Lint
      run: |
        go get -u github.com/kevinburke/go-bindata/...
        go get -u golang.org/x/lint/golint
        go vet ./...
        golint ./...
    - name: Node Build
      working-directory: web
      run: yarn run build --no-progress --production
    - name: Go Build
      run: |
        go generate -v api/api.go
        go build -v -o bookmarks --tags "fts5"
